/* GENERATED by master/gen_params.py from master/params.py — do not edit */
#pragma once
#define FRX_PROTOCOL_VERSION 1
#define FRX_NPARAMS 20
#define FRX_HEADER_SIZE 40
#define FRX_PACKET_SIZE 120
enum frx_param {
    P_MODE = 0,
    P_ITERATIONS = 1,
    P_ZOOM = 2,
    P_CENTER_X = 3,
    P_CENTER_Y = 4,
    P_JULIA_X = 5,
    P_JULIA_Y = 6,
    P_ROTATION = 7,
    P_KALEIDO = 8,
    P_WARP = 9,
    P_HUE = 10,
    P_HUE_SPREAD = 11,
    P_HUE_SPEED = 12,
    P_CONTRAST = 13,
    P_BRIGHTNESS = 14,
    P_GLOW = 15,
    P_BEAT_PULSE = 16,
    P_BAR_SWING = 17,
    P_ENERGY = 18,
    P_BASS = 19,
};
static const char *FRX_PARAM_NAMES[FRX_NPARAMS] = {
    "mode", "iterations", "zoom", "center_x", "center_y", "julia_x", "julia_y", "rotation", "kaleido", "warp", "hue", "hue_spread", "hue_speed", "contrast", "brightness", "glow", "beat_pulse", "bar_swing", "energy", "bass"
};
static const float FRX_PARAM_DEFAULTS[FRX_NPARAMS] = {
    0.0f, 160.0f, 0.6f, -0.55f, 0.0f, -0.75f, 0.12f, 0.0f, 0.0f, 0.0f, 0.62f, 1.2f, 0.08f, 1.1f, 1.0f, 0.35f, 0.4f, 0.2f, 0.0f, 0.0f
};
/* 1 = discrete (snap), 0 = continuous (smooth) */
static const unsigned char FRX_PARAM_DISCRETE[FRX_NPARAMS] = {
    1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
