#!/usr/bin/env python3
"""Regenerate the derived parameter tables from params.py. Run from anywhere."""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from params import PARAMS, NPARAMS, PROTOCOL_VERSION, HEADER, PACKET_SIZE

BANNER = "GENERATED by master/gen_params.py from master/params.py — do not edit"

# --- C header --------------------------------------------------------------
h = [f"/* {BANNER} */", "#pragma once",
     f"#define FRX_PROTOCOL_VERSION {PROTOCOL_VERSION}",
     f"#define FRX_NPARAMS {NPARAMS}",
     f"#define FRX_HEADER_SIZE {HEADER.size}",
     f"#define FRX_PACKET_SIZE {PACKET_SIZE}",
     "enum frx_param {"]
for i, p in enumerate(PARAMS):
    h.append(f"    P_{p[0].upper()} = {i},")
h.append("};")
h.append("static const char *FRX_PARAM_NAMES[FRX_NPARAMS] = {")
h.append("    " + ", ".join(f'"{p[0]}"' for p in PARAMS))
h.append("};")
h.append("static const float FRX_PARAM_DEFAULTS[FRX_NPARAMS] = {")
h.append("    " + ", ".join(f"{float(p[4])}f" for p in PARAMS))
h.append("};")
h.append("/* 1 = discrete (snap), 0 = continuous (smooth) */")
h.append("static const unsigned char FRX_PARAM_DISCRETE[FRX_NPARAMS] = {")
h.append("    " + ", ".join("1" if p[5] == 'i' else "0" for p in PARAMS))
h.append("};")
open(os.path.join(ROOT, "renderer", "params.h"), "w").write("\n".join(h) + "\n")

# --- GLSL prelude ------------------------------------------------------------
g = ["#version 300 es", f"// {BANNER}", "precision highp float;", "precision highp int;",
     f"#define NP {NPARAMS}"]
for i, p in enumerate(PARAMS):
    g.append(f"#define P_{p[0].upper()} u_p[{i}]")
open(os.path.join(ROOT, "renderer", "shaders", "params.glsl"), "w").write("\n".join(g) + "\n")

# --- JS table ----------------------------------------------------------------
js = [f"// {BANNER}",
      f"window.FRX_PROTOCOL_VERSION = {PROTOCOL_VERSION};",
      "window.FRX_PARAMS = " + json.dumps(
          [dict(key=p[0], label=p[1], min=p[2], max=p[3], def_=p[4], kind=p[5], auto=p[6], group=p[7], tip=p[8])
           for p in PARAMS], indent=1) + ";"]
os.makedirs(os.path.join(ROOT, "web"), exist_ok=True)
open(os.path.join(ROOT, "web", "params.js"), "w").write("\n".join(js) + "\n")
print(f"ok: {NPARAMS} params, packet {PACKET_SIZE} bytes")
